#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service(){
    procd_open_instance utaipfwd
    procd_set_param command utaipfwd -f /etc/utaipfwd.ini
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_set_param file /etc/utaipfwd.ini # /etc/init.d/your_service reload will restart the daemon if these files have changed
    procd_set_param stdout 1 # forward stdout of the command to logd
    procd_set_param stderr 1 # same for stderr
    procd_set_param pidfile /var/run/utaipfwd.pid # write a pid file on instance start and remove it on stop
    procd_close_instance
}